### ISSUE TITLE
add caller guard to all public functions

### ISSUE THREAD

**Issue by goastler** [prosopo/protocol#136]

**Comment by forgetso** [comment]
Checking if the caller is the owner of the dapp, is the provider account, etc. dependent on the function being called.

**Comment by forgetso** [comment]
- [x] provider_register already checked
- [x] provider_update already checked
- [x] provider_change_status **private**
- [x] provider_deregister already checked
- [x] provider_unstake already checked
- [x] provider_add_dataset already checked
- [ ] dapp_register needs to be modified to force the caller to be the owner
- [x] dapp_update already checks that the caller is the owner
- [ ] dapp_fund should anybody be allowed to fund the dapp account?
- [x] dapp_cancel already checks that caller is the owner of the contract
- [x] dapp_deregister **private**
- [x] dapp_user_commit prevents dapps from submitting user commits. Any other accounts can submit
- [x] create_new_dapp_user **private**
- [x] provider_approve checks provider is active and is the provider for the commitment being approved
- [x] provider_disapprove checks provider is active and is the provider for the commitment being disapproved
- [x] pay_fee **private**
- [x] refund_transaction_fee **private**
- [x] all other functions are reads
