### ISSUE TITLE
do all user_commitments need to be stored?

### ISSUE THREAD

**Issue by goastler** [prosopo/protocol#143]

**Comment by goastler** [comment]
It makes sense to store pending commitments, as these need to be looked up in the future. But approved / disapproved commitments need not be stored, especially if we use events to record their occurrence. The events can be traversed at any point in time for auditing, etc, so we do not need them in the current state of the contract

**Comment by forgetso** [comment]
No, they do not need to be stored and this is actually an attack vector as malicious agents could fill up the contract with crap, increasing gas costs for us and our users. Therefore, store only the last `n` commitments.

**Comment by forgetso** [comment]
Associated with https://github.com/prosopo/protocol/issues/102
