### ISSUE TITLE
make a deploy script for updating the contract

### ISSUE THREAD

**Issue by goastler** [prosopo/protocol#146]

**Comment by goastler** [comment]
this should rebuild the contract, extract the contract address, update the .env files for all repos accordingly and replace the metadata / abi in other repos too

assume scripts / protocol / workspaces all in one dir

**Comment by forgetso** [comment]
contract address does not change with set_code_hash

**Comment by goastler** [comment]
investigate how this works with set_code_hash

**Comment by goastler** [comment]
close in favour of DAO / proxy
