### ISSUE TITLE
decide whether to use getters or storage api

### ISSUE THREAD

**Issue by goastler** [prosopo/protocol#206]

**Comment by goastler** [comment]
https://github.com/paritytech/ink/issues/782#issuecomment-1439077866

**Comment by goastler** [comment]
- getters allow for usage with polkadotjs apps whereas storage api does not.
- getters are also clearer
- getters add extra developer overhead to maintain
- getters add code size to the contract

**Comment by forgetso** [comment]
TODO: Compile a version of the contract without any getters.

**Comment by forgetso** [comment]
-  getters are potentially security risk as removing them obfuscates the contract storage

**Comment by goastler** [comment]
- using storage api forgoes the nice polkadotjs UI, but that's good for deterring random people from inspecting our contract storage

**Comment by goastler** [comment]
woudl have to put the storage api getters in contracts repo
