### ISSUE TITLE
How do we trust the `transaction_fee` sent by the provider?

### ISSUE THREAD

**Issue by forgetso** [prosopo/protocol#217]
This is fee that is to be repaid to the `DappUser`. The Provider could manipulate it to be zero and avoid refunding any tx fees.

```
        #[ink(message)]
        pub fn provider_approve(
            &mut self,
            captcha_solution_commitment_id: Hash,
            transaction_fee: Balance,
        ) -> Result<(), Error> {
```

Are providers required to take part in event auditing and auto-report when things go wrong? This would result in a Provider being slashed if the majority of Providers reported against them.

**Comment by goastler** [comment]
now irrelevant with the approval only system
