### ISSUE TITLE
can the block time become an issue for provider and user committing in the same block?

### ISSUE THREAD

**Issue by goastler** [prosopo/protocol#228]

**Comment by goastler** [comment]
E.g. user commits in block 3. Provider receives same commit from the user. Provider queries the contract, still on block 3, and cannot find the user's commit because the block has not rolled over yet. Had the block rollover have happened before the provider received the user's commit, then everything would be fine.

**Comment by goastler** [comment]
we haven't hit this issue yet during testing because we're using instant_seal

**Comment by forgetso** [comment]
Good point - should come out in testing with a substrate node. I'll give this a shot.

**Comment by forgetso** [comment]
Tested with 6s block time and all unit tests passed
