### ISSUE TITLE
implement slashing for when the user did not request a captcha, but the provider submitted a captcha commit for them

### ISSUE THREAD

**Issue by goastler** [prosopo/protocol#258]

**Comment by forgetso** [comment]
We are only allowing for approvals now so Providers cannot give bad reputation to accounts they don't own

They can put approvals on-chain for accounts they do own but they would need to wait for themselves to be chosen for their user account, which seems far fetched.

The more approvals they put on-chain, the less likely they will selected in future as they will end up out of sync with the Provider average approval volume.
