### ISSUE TITLE
rename commitments to solutions

### ISSUE THREAD

**Issue by goastler** [prosopo/protocol#276]

**Comment by forgetso** [comment]
This one is more difficult than at first seems. There's a concept of solutions which are individual solutions to captchas. A commitment is the rolled up merkle root of all of the captchas the user has solved in a captcha challenge event.

So mongo has collections called solutions and commitments and they're quite heavily baked into the logic.
From a contract point of view, it is only ever dealing with commitments
The solutions only live on the provider.

**Comment by goastler** [comment]
Decided against doing this in the end. Solutions are different to commitments
