### ISSUE TITLE
use proxy pattern for contract upgrades

### ISSUE THREAD

**Issue by forgetso** [prosopo/protocol#99]

**Comment by goastler** [comment]
need to be careful about storage and not sharing storage locations when the implementation contract differs from the proxy

**Comment by goastler** [comment]
setCodeHash is one way of doing it

https://github.com/paritytech/ink/tree/master/examples/upgradeable-contracts

**Comment by goastler** [comment]
https://github.com/paritytech/ink/tree/master/examples/upgradeable-contracts

**Comment by forgetso** [comment]
Needed to avoid client servers from becoming out of sync with the real contract address.
